services:
  vrpelvisim-deepdrr-zmq:
    image: ghcr.io/arcadelab/vrpelvisim-deepdrr-zmq:main
    restart: unless-stopped
    ports:
      - "40120:40120"
      - "40121:40121"
      - "40122:40122"
    environment:
      - PATIENT_DATA_DIR=/patientdata
      - LOG_DIR=/logdata
      - REPLAY_LOG_DIR=/logdata/vrpslogs
      - SNAPSHOT_LOG_DIR=/logdata/sslogs
      - DEEPDRR_DATA_DIR=/deepdrrcache
    volumes:
      # Patient data
      - type: bind
        source: ${DOCKER_PATIENT_DATA_DIR}
        target: /patientdata
        read_only: true
      - type: bind
        source: ${DOCKER_LOG_DIR}
        target: /logdata
        read_only: false
      # DeepDRR Cache Volume
      - type: volume
        source: deepdrrcache
        target: /deepdrrcache
        read_only: false
    pull_policy: build
    build:
      context: ./
      dockerfile: ./Dockerfile
    deploy:
      resources:
        # limits:
          # cpus: '0.50'
          # memory: 12G
        reservations:
          # cpus: '0.25'
          # memory: 8G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, graphics]
volumes:
  deepdrrcache:
    driver: local