# name: deepdrr_zmq
name: pelvisvr-deepdrr-zmq
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  # - pytorch-cuda=11.7
  # - pycuda
  - pip
  - pip:
      # - deepdrr
      - pyzmq
      - pycapnp
      - typer
