name: pelvisvr-deepdrr-zmq
channels:
  - pytorch
  - "nvidia/label/cuda-11.8.0"
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cuda-toolkit
  - cuda-runtime
  - cuda-nvprof
  - cuda-gdb
  - cuda-profiler-api
  - pip
  - pip:
      # - git+https://github.com/arcadelab/deepdrr.git@dev
      - git+https://github.com/arcadelab/deepdrr.git@ac1c3820b16377bf87a8fa1c2dbec4ce7c0bf0d5
      - cupy-cuda11x
      - ipywidgets
      - joblib
      - jupyter
      - more_itertools
      - pipenv
      - pyzmq
      - pycapnp
      - scipy
      - tqdm
      - typer
