name: pelvisvr-deepdrr-zmq
channels:
  - pytorch
  - "nvidia/label/cuda-11.8.0"
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cuda-toolkit
  - cuda-runtime
  - cuda-nvprof
  - cuda-gdb
  - cuda-profiler-api
  - pip
  - pip:
      - git+https://github.com/arcadelab/deepdrr.git@dev
      - cupy-cuda11x
      - pyzmq
      - pycapnp
      - typer
      - scipy
      - joblib
      - more_itertools
      - pipenv
      - tqdm
      - ipywidgets
      - jupyter  