name: vrpelvisim-deepdrr-zmq
channels:
  - pytorch
  - "nvidia/label/cuda-11.8.0"
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cuda-toolkit
  - cuda-runtime
  - cuda-nvprof
  - cuda-gdb
  - cuda-profiler-api
  - pip
  - pip:
      # - git+https://github.com/arcadelab/deepdrr.git@dev
      - git+https://github.com/arcadelab/deepdrr.git@43b45a8674541f746aa8d92e84acfd983989e194
      - aiofiles
      - cupy-cuda11x
      - ipywidgets
      - joblib
      - jupyter
      - more_itertools
      - pipenv
      - pyzmq
      - pycapnp
      - pymeshfix
      - scipy
      - tqdm
      - typer
