name: pelvisvr-deepdrr-zmq
channels:
  - pytorch
  - "nvidia/label/cuda-12.3.2"
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - cuda-toolkit
  - cuda-runtime
  - cuda-nvprof
  - cuda-gdb
  - cuda-profiler-api
  - pip
  - pip:
      - git+https://github.com/arcadelab/deepdrr.git@dev
      - pyzmq
      - pycapnp
      - typer
      - scipy
      - joblib
      - pipenv
      - tqdm
      - ipywidgets
      - jupyter
      - more_itertools